### PR TITLE
support start startovirt vm with image

### PR DESCRIPTION
**Pull request by Vanient**
After this , we support using kuasar to boot startovirt VM with **block image as rootfs**.
Specifify image_path in config file to try it~

### CODE REVIEW

**Comment by Burning1020** [comment]
Please provide some description about this.

**Comment by Vanient** [comment]
> on


> Please provide some description about this.

Done

**Comment by Vanient** [comment]
> Please provide some description about this.

DONE

**Review by Burning1020 — APPROVED** [review]
LGTM

**Review by flyflypeng — CHANGES_REQUESTED** [review]
It is recommended that a unit test case be added to test the image parameter in the vmm/sandbox/src/stratovirt/config.rs file.

**Review by flyflypeng — APPROVED** [review]
LGTM

**Pull request merged**
